### ISSUE TITLE
[FEATURE] Allow installation on VSCode Insider

### ISSUE THREAD

**Issue by krisavi** [A-0-5/gostmortem-table#10]
### Feature Description

Getting error like:
`Can't install 'aos.gostmortem-table' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.83.0-insider).`

Would be good to be able to install on insider versions of VSCode as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by A-0-5** [comment]
Hi @krisavi 
Apologies for the delayed response as I was travelling and did not get a chance to look at the issue board. I'll look into this and post an update at the earliest

**Comment by A-0-5** [comment]
Hi @krisavi ,
I was able to look at the package.json for this extension. When I developed this extension, I had developed it using 1.86.0 
https://github.com/A-0-5/gostmortem-table/blob/2163363762d9d27a9094a8bd088710cf65a92db5/package.json#L14

This [Link](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#visual-studio-code-compatibility) explains how the compatibility works.

So this supports both insiders and stable channels above 1.86.0 . Is there any specific blocker preventing you to upgrade you vscode instance to 1.86 or above insider channel. If so I can explore the code to see if I have any APIs which require the 1.86.X  sdk and then downgrade if the extension would work with 1.83.X .

If upgrading your setup is an option I would request you to try doing so to any version above 1.86.0 either insider or stable , whichever works for you. 

If that is not possible I will go ahead and explore the extension compatibility with 1.83 apis. 

Please do let me know if you can upgrade to a version 1.86.X or above (stable or insiders) and if that works.

**Comment by A-0-5** [comment]
Hi @krisavi 
Did the upgrade to 1.86.X fix the issue you were facing?
