### ISSUE TITLE
[FEATURE] Please add gostmortem to the Open VSX marketplace

### ISSUE THREAD

**Issue by christophberger** [A-0-5/gostmortem-table#5]
### Feature Description

Great extension! I would love to see this on https://open-vsx.org, too. (VSCodium connects to Open VSX rather than the Microsoft VSCode Marketplace.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by A-0-5** [comment]
Update : I have requested for a namespace to publish this extension as per https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#4-create-the-namespace
by creating the following issue https://github.com/EclipseFdn/open-vsx.org/issues/2393 . 
Once that is done I will publish and update this ticket.

**Comment by christophberger** [comment]
Awesome! Thank you, @A-0-5!

**Comment by A-0-5** [comment]
Hi @christophberger ,
The extension has been published to open-vsx.org and is available for download at 
https://open-vsx.org/extension/AOS/gostmortem-table

I once again thank you for reporting this issue. I will close this issue as completed for now. In case you feel something has been missed out in this please feel free to reopen this issue.

Thanks
@A-0-5
